
version: "3.1"

networks:
  TS-EXPRESS-TEST:
    driver: bridge

services:
  # redis:
  #   container_name: "ts-express-test-redis"
  #   image: "bitnami/redis:6.0.8"
  #   environment:
  #     REDIS_PASSWORD: password123
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - TS-EXPRESS-TEST
  mongodb_bitnami:
    container_name: "ts-express-mongodb"
    image: "bitnami/mongodb:latest"
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_USERNAME: user
      MONGODB_PASSWORD: password
      MONGODB_DATABASE: database
    ports:
      # expose it on 27018 to avoid conflict with the production mongodb
      - 27017:27017
    networks:
      - TS-EXPRESS-TEST
