
version: "3.1"

networks:
  REDBULL_NETWORK-TEST:
    driver: bridge

services:
  redis:
    container_name: "redbulltest-redis"
    image: "bitnami/redis:6.0.8"
    environment:
      REDIS_PASSWORD: password123
    ports:
      - 6379:6379
    networks:
      - REDBULL_NETWORK-TEST
  mongodb_bitnami:
    container_name: "redbulltest-mongodb"
    image: "bitnami/mongodb:latest"
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_USERNAME: user
      MONGODB_PASSWORD: password
      MONGODB_DATABASE: database
    ports:
      - 27017:27017
    networks:
      - REDBULL_NETWORK-TEST
