version: "3.1"

networks:
  TS-EXPRESS:
    driver: bridge

services:
  # redis:
  #   container_name: "ts-express-redis"
  #   image: "bitnami/redis:6.0.8"
  #   environment:
  #     REDIS_PASSWORD: password123
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - TS-EXPRESS
  mongodb_bitnami:
    container_name: "ts-express-mongodb"
    image: "bitnami/mongodb:latest"
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_USERNAME: user
      MONGODB_PASSWORD: password
      MONGODB_DATABASE: database
    ports:
      - 27017:27017
    networks:
      - TS-EXPRESS

# DATABASE_URL=mongodb://user:password@127.0.0.1:27017/database
