on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
name: CI

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Packages
        run: npm install

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: npm run lint

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Test Containers
        run: docker compose -f docker-compose.test.yml up -d
      - name: Sleep for 10s
        uses: juliangruber/sleep-action@v1
        with:
          time: 10s
      - name: Test
        run: export DATABASE_URL=postgres://postgres:postgres@127.0.0.1:5432/postgres && npm run test
